import blurMap from "@/lib/content/blur.json";
import type { Media } from "@/lib/types";

const map = blurMap as Record<string, string>;

/**
 * Spread onto <Image> to get a blurred preview while a lazy image loads.
 * Returns nothing when no placeholder exists, so it degrades silently rather
 * than throwing on an unknown path.
 *
 * Generated by `node scripts/generate-blur.mjs`, for the couple of images
 * that are still local (the homepage hero, the About page photo). Anything
 * coming from Sanity carries its own LQIP — see `mediaBlurProps` below.
 */
export function blurProps(src: string) {
  const blurDataURL = map[src];
  return blurDataURL ? { placeholder: "blur" as const, blurDataURL } : {};
}

/**
 * Same as `blurProps`, but takes a full `Media` object — Sanity-backed
 * content already carries `blurDataURL` on the object itself (from the
 * asset's `metadata.lqip`, set in lib/sanity/queries.ts), so this uses that
 * directly when present, and only falls back to the local path lookup for
 * content that still lives in `lib/content/*`.
 */
export function mediaBlurProps(media: Media) {
  if (media.blurDataURL) {
    return { placeholder: "blur" as const, blurDataURL: media.blurDataURL };
  }
  return blurProps(media.src);
}
