import blurMap from "@/lib/content/blur.json";

const map = blurMap as Record<string, string>;

/**
 * Spread onto <Image> to get a blurred preview while a lazy image loads.
 * Returns nothing when no placeholder exists, so it degrades silently rather
 * than throwing on an unknown path.
 *
 * Generated by `node scripts/generate-blur.mjs`. When Sanity is wired, its
 * asset metadata supplies the LQIP instead and this becomes local-only.
 */
export function blurProps(src: string) {
  const blurDataURL = map[src];
  return blurDataURL ? { placeholder: "blur" as const, blurDataURL } : {};
}
